/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TracedService_H
#define TracedService_H

#include <thrift/TDispatchProcessor.h>
#include "tracetest_types.h"

namespace jaegertracing { namespace crossdock { namespace thrift {

class TracedServiceIf {
 public:
  virtual ~TracedServiceIf() {}
  virtual void startTrace(TraceResponse& _return, const StartTraceRequest& request) = 0;
  virtual void joinTrace(TraceResponse& _return, const JoinTraceRequest& request) = 0;
};

class TracedServiceIfFactory {
 public:
  typedef TracedServiceIf Handler;

  virtual ~TracedServiceIfFactory() {}

  virtual TracedServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TracedServiceIf* /* handler */) = 0;
};

class TracedServiceIfSingletonFactory : virtual public TracedServiceIfFactory {
 public:
  TracedServiceIfSingletonFactory(const boost::shared_ptr<TracedServiceIf>& iface) : iface_(iface) {}
  virtual ~TracedServiceIfSingletonFactory() {}

  virtual TracedServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TracedServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<TracedServiceIf> iface_;
};

class TracedServiceNull : virtual public TracedServiceIf {
 public:
  virtual ~TracedServiceNull() {}
  void startTrace(TraceResponse& /* _return */, const StartTraceRequest& /* request */) {
    return;
  }
  void joinTrace(TraceResponse& /* _return */, const JoinTraceRequest& /* request */) {
    return;
  }
};

typedef struct _TracedService_startTrace_args__isset {
  _TracedService_startTrace_args__isset() : request(false) {}
  bool request :1;
} _TracedService_startTrace_args__isset;

class TracedService_startTrace_args {
 public:

  static const char* ascii_fingerprint; // = "75E1EFBE012B6047AC6FC549B40DF573";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0xE1,0xEF,0xBE,0x01,0x2B,0x60,0x47,0xAC,0x6F,0xC5,0x49,0xB4,0x0D,0xF5,0x73};

  TracedService_startTrace_args(const TracedService_startTrace_args&);
  TracedService_startTrace_args& operator=(const TracedService_startTrace_args&);
  TracedService_startTrace_args() {
  }

  virtual ~TracedService_startTrace_args() throw();
  StartTraceRequest request;

  _TracedService_startTrace_args__isset __isset;

  void __set_request(const StartTraceRequest& val);

  bool operator == (const TracedService_startTrace_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TracedService_startTrace_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TracedService_startTrace_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_startTrace_args& obj);
};


class TracedService_startTrace_pargs {
 public:

  static const char* ascii_fingerprint; // = "75E1EFBE012B6047AC6FC549B40DF573";
  static const uint8_t binary_fingerprint[16]; // = {0x75,0xE1,0xEF,0xBE,0x01,0x2B,0x60,0x47,0xAC,0x6F,0xC5,0x49,0xB4,0x0D,0xF5,0x73};


  virtual ~TracedService_startTrace_pargs() throw();
  const StartTraceRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_startTrace_pargs& obj);
};

typedef struct _TracedService_startTrace_result__isset {
  _TracedService_startTrace_result__isset() : success(false) {}
  bool success :1;
} _TracedService_startTrace_result__isset;

class TracedService_startTrace_result {
 public:

  static const char* ascii_fingerprint; // = "7822BCFD5E6B23D1ECCF9A542B99CA5F";
  static const uint8_t binary_fingerprint[16]; // = {0x78,0x22,0xBC,0xFD,0x5E,0x6B,0x23,0xD1,0xEC,0xCF,0x9A,0x54,0x2B,0x99,0xCA,0x5F};

  TracedService_startTrace_result(const TracedService_startTrace_result&);
  TracedService_startTrace_result& operator=(const TracedService_startTrace_result&);
  TracedService_startTrace_result() {
  }

  virtual ~TracedService_startTrace_result() throw();
  TraceResponse success;

  _TracedService_startTrace_result__isset __isset;

  void __set_success(const TraceResponse& val);

  bool operator == (const TracedService_startTrace_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TracedService_startTrace_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TracedService_startTrace_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_startTrace_result& obj);
};

typedef struct _TracedService_startTrace_presult__isset {
  _TracedService_startTrace_presult__isset() : success(false) {}
  bool success :1;
} _TracedService_startTrace_presult__isset;

class TracedService_startTrace_presult {
 public:

  static const char* ascii_fingerprint; // = "7822BCFD5E6B23D1ECCF9A542B99CA5F";
  static const uint8_t binary_fingerprint[16]; // = {0x78,0x22,0xBC,0xFD,0x5E,0x6B,0x23,0xD1,0xEC,0xCF,0x9A,0x54,0x2B,0x99,0xCA,0x5F};


  virtual ~TracedService_startTrace_presult() throw();
  TraceResponse* success;

  _TracedService_startTrace_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const TracedService_startTrace_presult& obj);
};

typedef struct _TracedService_joinTrace_args__isset {
  _TracedService_joinTrace_args__isset() : request(false) {}
  bool request :1;
} _TracedService_joinTrace_args__isset;

class TracedService_joinTrace_args {
 public:

  static const char* ascii_fingerprint; // = "C9866C489F3BFF411AD949D13837452D";
  static const uint8_t binary_fingerprint[16]; // = {0xC9,0x86,0x6C,0x48,0x9F,0x3B,0xFF,0x41,0x1A,0xD9,0x49,0xD1,0x38,0x37,0x45,0x2D};

  TracedService_joinTrace_args(const TracedService_joinTrace_args&);
  TracedService_joinTrace_args& operator=(const TracedService_joinTrace_args&);
  TracedService_joinTrace_args() {
  }

  virtual ~TracedService_joinTrace_args() throw();
  JoinTraceRequest request;

  _TracedService_joinTrace_args__isset __isset;

  void __set_request(const JoinTraceRequest& val);

  bool operator == (const TracedService_joinTrace_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TracedService_joinTrace_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TracedService_joinTrace_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_joinTrace_args& obj);
};


class TracedService_joinTrace_pargs {
 public:

  static const char* ascii_fingerprint; // = "C9866C489F3BFF411AD949D13837452D";
  static const uint8_t binary_fingerprint[16]; // = {0xC9,0x86,0x6C,0x48,0x9F,0x3B,0xFF,0x41,0x1A,0xD9,0x49,0xD1,0x38,0x37,0x45,0x2D};


  virtual ~TracedService_joinTrace_pargs() throw();
  const JoinTraceRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_joinTrace_pargs& obj);
};

typedef struct _TracedService_joinTrace_result__isset {
  _TracedService_joinTrace_result__isset() : success(false) {}
  bool success :1;
} _TracedService_joinTrace_result__isset;

class TracedService_joinTrace_result {
 public:

  static const char* ascii_fingerprint; // = "7822BCFD5E6B23D1ECCF9A542B99CA5F";
  static const uint8_t binary_fingerprint[16]; // = {0x78,0x22,0xBC,0xFD,0x5E,0x6B,0x23,0xD1,0xEC,0xCF,0x9A,0x54,0x2B,0x99,0xCA,0x5F};

  TracedService_joinTrace_result(const TracedService_joinTrace_result&);
  TracedService_joinTrace_result& operator=(const TracedService_joinTrace_result&);
  TracedService_joinTrace_result() {
  }

  virtual ~TracedService_joinTrace_result() throw();
  TraceResponse success;

  _TracedService_joinTrace_result__isset __isset;

  void __set_success(const TraceResponse& val);

  bool operator == (const TracedService_joinTrace_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TracedService_joinTrace_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TracedService_joinTrace_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TracedService_joinTrace_result& obj);
};

typedef struct _TracedService_joinTrace_presult__isset {
  _TracedService_joinTrace_presult__isset() : success(false) {}
  bool success :1;
} _TracedService_joinTrace_presult__isset;

class TracedService_joinTrace_presult {
 public:

  static const char* ascii_fingerprint; // = "7822BCFD5E6B23D1ECCF9A542B99CA5F";
  static const uint8_t binary_fingerprint[16]; // = {0x78,0x22,0xBC,0xFD,0x5E,0x6B,0x23,0xD1,0xEC,0xCF,0x9A,0x54,0x2B,0x99,0xCA,0x5F};


  virtual ~TracedService_joinTrace_presult() throw();
  TraceResponse* success;

  _TracedService_joinTrace_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const TracedService_joinTrace_presult& obj);
};

class TracedServiceClient : virtual public TracedServiceIf {
 public:
  TracedServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TracedServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void startTrace(TraceResponse& _return, const StartTraceRequest& request);
  void send_startTrace(const StartTraceRequest& request);
  void recv_startTrace(TraceResponse& _return);
  void joinTrace(TraceResponse& _return, const JoinTraceRequest& request);
  void send_joinTrace(const JoinTraceRequest& request);
  void recv_joinTrace(TraceResponse& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TracedServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TracedServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TracedServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_startTrace(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_joinTrace(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TracedServiceProcessor(boost::shared_ptr<TracedServiceIf> iface) :
    iface_(iface) {
    processMap_["startTrace"] = &TracedServiceProcessor::process_startTrace;
    processMap_["joinTrace"] = &TracedServiceProcessor::process_joinTrace;
  }

  virtual ~TracedServiceProcessor() {}
};

class TracedServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TracedServiceProcessorFactory(const ::boost::shared_ptr< TracedServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TracedServiceIfFactory > handlerFactory_;
};

class TracedServiceMultiface : virtual public TracedServiceIf {
 public:
  TracedServiceMultiface(std::vector<boost::shared_ptr<TracedServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TracedServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TracedServiceIf> > ifaces_;
  TracedServiceMultiface() {}
  void add(boost::shared_ptr<TracedServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void startTrace(TraceResponse& _return, const StartTraceRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->startTrace(_return, request);
    }
    ifaces_[i]->startTrace(_return, request);
    return;
  }

  void joinTrace(TraceResponse& _return, const JoinTraceRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->joinTrace(_return, request);
    }
    ifaces_[i]->joinTrace(_return, request);
    return;
  }

};

}}} // namespace

#endif
