name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\hunter
        key: ${{ runner.os }}-hunter-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-hunter-

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure
      run: cmake -Bbuild

    - name: Build
      run: cmake --build build -j4

    - name: Test
      run: |
        cd build
        ctest -V -C Debug --timeout 600
